"""add source endpoint and resources

Revision ID: 31d3c2e74173
Revises: 470a2e54120c
Create Date: 2022-12-07 12:26:09.496456

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "31d3c2e74173"
down_revision = "470a2e54120c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_endpoint_dataset",
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("dataset", sa.Text(), nullable=False),
        sa.Column("endpoint_url", sa.Text(), nullable=False),
        sa.Column("documentation_url", sa.Text(), nullable=True),
        sa.Column("entry_date", sa.Date(), nullable=True),
        sa.Column("organisation_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisation.organisation"],
        ),
        sa.PrimaryKeyConstraint("source", "endpoint", "dataset"),
    )
    op.create_table(
        "resources",
        sa.Column("resource", sa.Text(), nullable=False),
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("endpoint_id", sa.Text(), nullable=False),
        sa.Column("dataset_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id", "endpoint_id", "dataset_id"],
            [
                "source_endpoint_dataset.source",
                "source_endpoint_dataset.endpoint",
                "source_endpoint_dataset.dataset",
            ],
        ),
        sa.PrimaryKeyConstraint("resource"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("resources")
    op.drop_table("source_endpoint_dataset")
    # ### end Alembic commands ###
