"""drop entities

Revision ID: 3ae1cc4edeb7
Revises: 397578893553
Create Date: 2022-12-13 11:50:22.813481

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3ae1cc4edeb7"
down_revision = "397578893553"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("entity")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entity",
        sa.Column("entity", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("dataset", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("start_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("end_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("entry_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column(
            "geojson",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "json",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("prefix", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("reference", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "organisation_entity", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["organisation_entity"],
            ["organisation.entity"],
            name="entity_organisation_entity_fkey",
        ),
        sa.PrimaryKeyConstraint("entity", name="entity_pkey"),
    )
    # ### end Alembic commands ###
