"""initial migration

Revision ID: 470a2e54120c
Revises:
Create Date: 2022-11-30 11:21:51.163813

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "470a2e54120c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dataset",
        sa.Column("dataset", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("dataset"),
    )
    op.create_table(
        "organisation",
        sa.Column("organisation", sa.Text(), nullable=False),
        sa.Column("entity", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("organisation"),
        sa.UniqueConstraint("entity"),
    )
    op.create_table(
        "entity",
        sa.Column("entity", sa.BigInteger(), nullable=False),
        sa.Column("dataset", sa.Text(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("entry_date", sa.Date(), nullable=True),
        sa.Column("geojson", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("json", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("prefix", sa.Text(), nullable=True),
        sa.Column("reference", sa.Text(), nullable=True),
        sa.Column("organisation_entity", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organisation_entity"],
            ["organisation.entity"],
        ),
        sa.PrimaryKeyConstraint("entity"),
    )
    op.create_table(
        "organisation_dataset",
        sa.Column("organisation", sa.Text(), nullable=True),
        sa.Column("dataset", sa.Text(), nullable=True),
        sa.Column("project", sa.Text(), nullable=True),
        sa.Column("project_name", sa.Text(), nullable=True),
        sa.Column("provision_reason", sa.Text(), nullable=True),
        sa.Column("provision_reason_name", sa.Text(), nullable=True),
        sa.Column("project_status", sa.Text(), nullable=True),
        sa.Column("project_status_description", sa.Text(), nullable=True),
        sa.Column("specification", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["dataset"],
            ["dataset.dataset"],
        ),
        sa.ForeignKeyConstraint(
            ["organisation"],
            ["organisation.organisation"],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("organisation_dataset")
    op.drop_table("entity")
    op.drop_table("organisation")
    op.drop_table("dataset")
    # ### end Alembic commands ###
