"""Initial migration.

Revision ID: 533a24fa186f
Revises:
Create Date: 2022-11-21 14:51:57.388064

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "533a24fa186f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organisation",
        sa.Column("organisation", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("entity", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("organisation"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("organisation")
    # ### end Alembic commands ###
