"""Initial migration

Revision ID: 53735f1eac7a
Revises:
Create Date: 2022-11-29 13:47:34.628733

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "53735f1eac7a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dataset",
        sa.Column("dataset", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("dataset"),
    )
    op.create_table(
        "project",
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "provider",
        sa.Column("entity", sa.BigInteger(), nullable=False),
        sa.Column("organisation", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("entity"),
        sa.UniqueConstraint("organisation"),
    )
    op.create_table(
        "entity",
        sa.Column("entity", sa.BigInteger(), nullable=False),
        sa.Column("dataset", sa.Text(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("entry_date", sa.Date(), nullable=True),
        sa.Column("geojson", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("json", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("prefix", sa.Text(), nullable=True),
        sa.Column("reference", sa.Text(), nullable=True),
        sa.Column("organisation_entity", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organisation_entity"],
            ["provider.entity"],
        ),
        sa.PrimaryKeyConstraint("entity"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("entity")
    op.drop_table("provider")
    op.drop_table("project")
    op.drop_table("dataset")
    # ### end Alembic commands ###
