"""add sources

Revision ID: af8a21baf398
Revises: 470a2e54120c
Create Date: 2022-12-05 15:51:22.274666

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "af8a21baf398"
down_revision = "470a2e54120c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source",
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("endpoint", sa.Text(), nullable=True),
        sa.Column("collection", sa.Text(), nullable=True),
        sa.Column("dataset", sa.Text(), nullable=True),
        sa.Column("documentation_url", sa.Text(), nullable=True),
        sa.Column("endpoint_url", sa.Text(), nullable=True),
        sa.Column("resource", sa.Text(), nullable=True),
        sa.Column("organisation", sa.Text(), nullable=True),
        sa.Column("organisation_entity", sa.BigInteger(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("source")
    # ### end Alembic commands ###
