"""Add entity table

Revision ID: d46bcfb5e741
Revises: 6c464e673772
Create Date: 2022-11-25 11:00:10.759406

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d46bcfb5e741"
down_revision = "6c464e673772"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entity",
        sa.Column("entity", sa.BigInteger(), nullable=False),
        sa.Column("dataset", sa.Text(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("entry_date", sa.Date(), nullable=True),
        sa.Column("geojson", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("json", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("organisation_entity", sa.Integer(), nullable=False),
        sa.Column("prefix", sa.Text(), nullable=True),
        sa.Column("reference", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("entity"),
    )
    with op.batch_alter_table("dataset", schema=None) as batch_op:
        batch_op.add_column(sa.Column("text", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dataset", schema=None) as batch_op:
        batch_op.drop_column("text")

    op.drop_table("entity")
    # ### end Alembic commands ###
