"""add endpoint entry date for sources

Revision ID: dd3f19fc1ec5
Revises: af8a21baf398
Create Date: 2022-12-06 12:12:08.477568

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "dd3f19fc1ec5"
down_revision = "af8a21baf398"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("source", schema=None) as batch_op:
        batch_op.add_column(sa.Column("entry_date", sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("source", schema=None) as batch_op:
        batch_op.drop_column("entry_date")

    # ### end Alembic commands ###
